import { styles } from "../App"

const items = [ 
    {name: "Leest", price: 55, desc: "An academic to-do lists for specific subjects.", img: "/images/leest.jpeg", sold: 132}, 
    {name: "Flashcard PDF", price: 46.8, desc: "Just upload a pdf of your school reviewer then boom. you have your 10 flashcards that is generated by AI from your uploaded PDF file.", img: "/images/flashcard.jpg", sold: 132}, 
    {name: "Flashcard Quiz", price: 60, desc: "Just another flashcard project but instead of just informing---this will formulate a question that will challenge you", img: "/images/flashcards-v2.jpeg", sold: 132}, 
    {name: "Lee+", price: 98.40, desc: "AI Powered by Grok API.", img: "/images/leeplus.jpeg", sold: 132}, 
    {name: "Denver Sticker", price: 100, desc: "A denver sticker consist of many variety, one is peeing in the toilet.", img: "/images/L.png", sold: 132},
    {name: "Keychain Dog", price: 9.81, desc: "A cute fancy keychain dog", img: "/images/L.png", sold: 132}
];

export const dashboard = (
    <main className={styles.main}>
        <div className={styles.sectionHeader}>
            <p className={styles.eyebrow}>MARKETPLACE</p>

            <h2 className={styles.title}>
            Top Item Sales
            </h2>

            <p className={styles.subtitle}>
            Popular products from the Lezada marketplace
            </p>
        </div>
        <section className={styles.itemGrid}>
        {items.map((item, index) => (
            <article
                key={index}
                className={styles.itemCard}
            >
                <div className={styles.imageContainer}>
                <img
                    src={item.img}
                    alt={item.name}
                    className={styles.itemImg}
                />
                </div>

                <div className={styles.itemContent}>
                    <div className={styles.itemTop}>
                        <h3 className={styles.itemName}>
                        {item.name}
                        </h3>

                        <span className={styles.itemPrice}>
                        ₱{item.price.toFixed(2)}
                        </span>
                    </div>

                    <p className={styles.itemDesc}>
                        {item.desc}
                    </p>

                    <div className={styles.itemBottom}>
                        <span className={styles.itemSold}>
                        {item.sold} sold
                        </span>

                        <button className={styles.viewBtn}>
                        View
                        </button>
                    </div>
                </div>
            </article>
            ))}
        </section>
    </main>
)