import { useState, useEffect } from "react"
import { styles } from "./App"
export default function App() {
  let [activeSection, setSection] = useState("PROFILE");
  let [isLoggedIn, setLogin] = useState(false);

  const user = {
    name: "Leeyam",
    profileImg: "/images/L.png",
    purchasesCount: 0,
    status: "Buyer"
  }

  const items = [ 
    {name: "Leest", price: 55, desc: "An academic to-do lists for specific subjects.", img: "/images/leest.jpeg", sold: 132}, 
    {name: "Flashcard PDF", price: 46.8, desc: "Just upload a pdf of your school reviewer then boom. you have your 10 flashcards that is generated by AI from your uploaded PDF file.", img: "/images/flashcard.jpg", sold: 132}, 
    {name: "Flashcard Quiz", price: 60, desc: "Just another flashcard project but instead of just informing---this will formulate a question that will challenge you", img: "/images/flashcards-v2.jpeg", sold: 132}, 
    {name: "Lee+", price: 98.40, desc: "AI Powered by Grok API.", img: "/images/leeplus.jpeg", sold: 132}, 
    {name: "Denver Sticker", price: 100, desc: "A denver sticker consist of many variety, one is peeing in the toilet.", img: "/images/L.png", sold: 132},
    {name: "Keychain Dog", price: 9.81, desc: "A cute fancy keychain dog", img: "/images/L.png", sold: 132}, ];

  return (
    <>
      <header className={styles.header}>
        <h1 className={styles.logo}>Lezada</h1>

        <nav className={styles.nav}>
          <a onClick={() => setSection("DASHBOARD")} className={styles.navBtn}>Dashboard</a>
          <a onClick={() => setSection("MY_CART")} className={styles.navBtn}>My Cart</a>
          <a onClick={() => setSection("PROFILE")} className={styles.navBtn}>Profile</a>
        </nav>
      </header>
      {
        activeSection === "DASHBOARD" && (
          <main className={styles.main}>
            <div className={styles.sectionHeader}>
              <p className={styles.eyebrow}>MARKETPLACE</p>

              <h2 className={styles.title}>
                Top Item Sales
              </h2>

              <p className={styles.subtitle}>
                Popular products from the Lezada marketplace
              </p>
            </div>
            <section className={styles.itemGrid}>
            {items.map((item, index) => (
                <article
                  key={index}
                  className={styles.itemCard}
                >
                  <div className={styles.imageContainer}>
                    <img
                      src={item.img}
                      alt={item.name}
                      className={styles.itemImg}
                    />
                  </div>

                  <div className={styles.itemContent}>
                    <div className={styles.itemTop}>
                      <h3 className={styles.itemName}>
                        {item.name}
                      </h3>

                      <span className={styles.itemPrice}>
                        ₱{item.price.toFixed(2)}
                      </span>
                    </div>

                    <p className={styles.itemDesc}>
                      {item.desc}
                    </p>

                    <div className={styles.itemBottom}>
                      <span className={styles.itemSold}>
                        {item.sold} sold
                      </span>

                      <button className={styles.viewBtn}>
                        View
                      </button>
                    </div>
                  </div>
                </article>
              ))}
            </section>
          </main>
        )
      }

      {/* PROFILE */}
      {/* PROFILE LOGIN*/}
      {activeSection === "PROFILE" && isLoggedIn === true && (
        <main>
          <div className={styles.profile.main}>
            {/* Banner */}
            <div className={styles.profile.banner} />
            {/* Profile information */}
            <div className={styles.profile.profileHolder}>
              <img
                className={styles.profile.profileImg}
                src={user.profileImg}
                alt={user.name}
              />
              <div className={styles.profile.userInfo}>
                <div>
                  <h1 className={styles.profile.name}>
                    {user.name}
                  </h1>
                  <p className={styles.profile.role}>
                    Lezada {user.status}
                  </p>
                </div>
                <span className={styles.profile.statusBadge}>
                  {user.status}
                </span>
              </div>
              {/* Statistics */}
              <div className={styles.profile.stats}>
                <div className={styles.profile.statCard}>
                  <p className={styles.profile.statValue}>
                    {user.purchasesCount}
                  </p>
                  <p className={styles.profile.statLabel}>
                    Items Purchased
                  </p>
                </div>
                <div className={styles.profile.statCard}>
                  <p className={styles.profile.statValue}>
                    ₱0.00
                  </p>
                  <p className={styles.profile.statLabel}>
                    Total Spent
                  </p>
                </div>
              </div>
              {/* Actions */}
              <div className={styles.profile.actions}>
                <button className={styles.profile.actionBtn}>
                  Edit Profile
                </button>
                <button className={styles.profile.primaryBtn}>
                  My Purchases
                </button>
              </div>
            </div>
          </div>
        </main>
      )}
      {/* PROFILE LOGOUT */}
      {activeSection === "PROFILE" && isLoggedIn === false && (
        <main className={styles.main}>
          <div className={styles.profile.unregisteredDiv.div}>
          <h1>Register/Login to Continue.</h1>
          <button className={styles.profile.unregisteredDiv.btn}>Register/Login</button>
          </div>
        </main>
      )}
    </>
  )
}
